In [86]:
import numpy as np

In [87]:
a= np.array ([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [88]:
type(a)

numpy.ndarray

In [89]:
#creating a 2d array 
a2= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [90]:
#creating a 3d array 
a3=np.array ([[[1,2,3],[4,5,6]],[[5,6,7],[8,9,10]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 5  6  7]
  [ 8  9 10]]]


In [91]:
print(a2.shape)
print(a2.ndim)
print(a2.dtype)

(2, 5)
2
int64


In [92]:
np.arange(10)
np.arange(1,11)
np.arange(1,11,2)


array([1, 3, 5, 7, 9])

In [93]:
np.random.randint(1,11, size=(2,3))

array([[7, 2, 5],
       [3, 3, 5]], dtype=int32)

In [94]:
x=np.array ([[7,2,3],
            [2,5,2,],
            [3,5,1]])
y=np.array([[1,8,3],
            [3,7,1],
            [2,5,3]])
print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 3]
 [3 7 1]
 [2 5 3]]


In [95]:
print(x*y)

[[ 7 16  9]
 [ 6 35  2]
 [ 6 25  3]]


In [96]:
print(x@y) #matrix multiplication

[[19 85 32]
 [21 61 17]
 [20 64 17]]


In [97]:
np.dot(x,y) #matrix multiplication

array([[19, 85, 32],
       [21, 61, 17],
       [20, 64, 17]])

In [98]:
x.prod() #product of all the elements of the array

np.int64(12600)

In [99]:
x.mean() #mean of all elemnets

np.float64(3.3333333333333335)

In [100]:
y.mean()

np.float64(3.6666666666666665)

In [101]:
x.mean(axis = 0) #column wise mean

array([4., 4., 2.])

In [102]:
y.mean(axis=1) #row wise mean


array([4.        , 3.66666667, 3.33333333])

In [103]:
print(x.sum())
print(x.std())
print(x.var())

30
1.8257418583505538
3.3333333333333335


In [104]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a,25))#1st quartile
print(np.percentile(a,50)) #median
print(np.percentile(a,75)) #3rd quartile

3.0
5.0
7.0


In [105]:
b=np.random.randint(11,100,(4,4))
print(b)

[[88 73 91 21]
 [38 23 69 28]
 [36 23 98 14]
 [29 34 14 29]]


In [106]:
print('2X8')
print(b.reshape(2,8))
print('8X2')
print(b.reshape(8,2))

2X8
[[88 73 91 21 38 23 69 28]
 [36 23 98 14 29 34 14 29]]
8X2
[[88 73]
 [91 21]
 [38 23]
 [69 28]
 [36 23]
 [98 14]
 [29 34]
 [14 29]]


In [107]:
x=np.random.randint(1,11,(5,5))
print(x)

[[ 9  1  6  4  5]
 [ 1  7  2  1  9]
 [ 9  3 10  2 10]
 [ 5  7  9  5  6]
 [ 1  6  5  8  4]]


In [108]:
print(x[0]) #1st row
print(x[0,1]) #1st row and 2 nd column's first element
print(x[-1])

print(x[:3])
print(x[3:])

[9 1 6 4 5]
1
[1 6 5 8 4]
[[ 9  1  6  4  5]
 [ 1  7  2  1  9]
 [ 9  3 10  2 10]]
[[5 7 9 5 6]
 [1 6 5 8 4]]
